version: '3.4'

services:
  tape_server:
    image: ticker_tape:0.1.1
    ports:
      - target: 8080
        published: 8080
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file
      options:
        max-size: 50m

  grafana:
    image: grafana_ticker:0.0.0
    ports:
      - target: 3000
        published: 3000
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - grafana:/var/lib/grafana
    logging:
      driver: json-file
      options:
        max-size: 50m

  influxdb:
    image: influxdb:1.5.2
    ports:
      - target: 8086
        published: 8086
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
       - influxdb:/var/lib/influxdb
    logging:
      driver: json-file
      options:
        max-size: 50m

  chronograf:
    image: chronograf:1.4.4.2
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - target: 8888
        published: 8888
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - chronograf:/var/lib/chronograf
    logging:
      driver: json-file
      options:
        max-size: 50m

volumes:
  grafana:
  influxdb:
  chronograf: